name: Lint & Format

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install RuboCop
        run: gem install rubocop
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: npx lint .

      - name: Run Prettier Check
        run: npx prettier --check .
